### PR TITLE
Add binding to show config

### PR DESCRIPTION
**Pull request by AeroNotix**
I have zero clue what I am doing.

I want to be able to display the current config.

Use-case: I don't want to save it wherever riemann-dash, or the host is deployed on something that is ephemeral, or doesn't have write perms to S3.

### CODE REVIEW

**Comment by AeroNotix** [comment]
Added templates instead of shoving raw strings into divs

**Comment by aphyr** [comment]
Mind adding your keybinding to the help view and quickhelp?

**Comment by AeroNotix** [comment]
Will do!

**Comment by AeroNotix** [comment]
Done.

**Comment by aphyr** [comment]
Woo, thanks AeroNotix!

**Pull request merged**
